# Generated by Django 5.2.1 on 2025-07-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='s_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
